mysite/mysite/main/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url

from . import teachers, parents

from rest_framework.urlpatterns import format_suffix_patterns

app_name = "main"

urlpatterns = [

    path("logs/", views.LogList.as_view()),
    path("", views.homepage, name="homepage"),
    path('tinymce/', include('tinymce.urls')),
    path("logout", views.logout_request, name="logout"),
    path("login", views.login_request, name="login"),
    path("welcome", views.welcome, name='welcome'),

    path('contact_us/', views.contact_us, name='contact_form'),
    path('accounts/signup/parent/', parents.ParentSignUpView.as_view(), name='parent_signup'),
    path('accounts/signup/parent/welcome/', views.welcome_parent, name='parent_welcome'),

    path('students/', views.list_students, name='list_students'),
    path('students/<section>', views.class_list, name='class_list'),

    path('stud_attendance/', views.stud_attendance, name='stud_attendance'),

    path('account/', views.account, name='account'),

    path('calendar-new', views.calendar_new, name= 'calendar-new'),
    url('password/', views.change_password, name='change_password'),

    path('child_stats/', views.child_stats, name='child_stats'),
    path('child_stats/<name>', views.indiv_stats, name='child_stats'),

    path('accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),

    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),

    url(r'broadcast$', views.broadcast_sms, name="default"),

    path('accounts/signup/teacher/welcome/', views.welcome, name='teacher_welcome'),
]

mysite/mysite/main/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser

from django.core.exceptions import ValidationError
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField

import datetime

class User(AbstractUser):
    is_teacher = models.BooleanField(default=False)
    is_parent = models.BooleanField(default=False)
    phone = PhoneNumberField()
    first_name = models.CharField(max_length=30)
    middle_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)


class Parent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)

class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    section_name = models.CharField(max_length=30)


class Student(models.Model):
    STATUS = (
        ('K', 'K'),
        ('GR1', 'GR1'),
        ('GR2', 'GR2'),
        ('GR3', 'GR3'),
        ('GR4', 'GR4'),
        ('GR5', 'GR5'),
        ('GR6', 'GR6'),
        ('GR7', 'GR7'),
        ('GR8', 'GR8'),
        ('GR9', 'GR9'),
        ('GR10', 'GR10'),
        ('GR11', 'GR11'),
        ('GR12', 'GR12'),
    )
    first_name = models.CharField(max_length=30)
    middle_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    year_level = models.CharField(max_length=30, choices=STATUS)
    section = models.CharField(max_length=30)
    id_number = models.IntegerField()
    email = models.CharField(max_length=30)
    parent = models.ManyToManyField(Parent)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)

class Section(models.Model):
    name = models.CharField(max_length=30)

class YearLevel(models.Model):
    STATUS = (
        ('K', 'K'),
        ('GR1', 'GR1'),
        ('GR2', 'GR2'),
        ('GR3', 'GR3'),
        ('GR4', 'GR4'),
        ('GR5', 'GR5'),
        ('GR6', 'GR6'),
        ('GR7', 'GR7'),
        ('GR8', 'GR8'),
        ('GR9', 'GR9'),
        ('GR10', 'GR10'),
        ('GR11', 'GR11'),
        ('GR12', 'GR12'),
    )
    level = models.CharField(max_length=30, choices=STATUS)
    section = models.ManyToManyField(Section)




class Log(models.Model):
    id_number = models.ForeignKey(Student, on_delete=models.CASCADE)
    time = models.TimeField()
    date = models.DateField()
    location = models.CharField(max_length=30)

    @property
    def get_html_url(self):
        url = reverse('main:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.location} </a>'


class Employee(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    @property
    def get_html_url(self):
        url = reverse('main:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'


class Contact_Message(models.Model):
    subject = models.CharField(max_length=100)
    email_address = models.EmailField()
    message = models.TextField()
    date = models.DateTimeField(default = datetime.datetime.now())

mysite/mysite/main/templates/main/account.html
{% extends 'templates/main/header.html' %}
{% block main %}
{% load static %}
<style>
    .card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  max-width: 500px;
  margin: auto;
  text-align: center;
}

.title {
  color: grey;
  font-size: 18px;
}

button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #3445b4;
  text-align: center;
  cursor: pointer;
  width: 100%;
  font-size: 18px;
}

a {
  text-decoration: none;
  font-size: 22px;
  color: black;
}

button:hover, a:hover {
  opacity: 0.7;
}

</style>

</br>
<div class="card">
  <img src="{% static "images/user.png" %}" alt="John" style="width:100%" align = "center">
  </br>
  <h1>{{user.first_name}} {{user.last_name}}</h1>
  <p class="title">{{user.email}}</p>

  {% if user.is_teacher %}
    <p>Teacher</p>
  {% else %}
    {% if user.is_parent %}
      <p class="title">{{user.phone}}</p>
      <p>Parent</p>
    {% else %}
      <p>Admin</p>
    {% endif %}
  {% endif%}

<!--  <p>< button>Change Password</button></p>-->
  <a button type="button" class="btn btn-primary" href="/password">Change Password</a>
  </br>
</div>

{%endblock%}

mysite/mysite/main/templates/main/change_password.html
{% extends 'templates/main/header.html' %}
{% block main %}

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save changes</button>
</form>

{%endblock%}

mysite/mysite/main/templates/main/child_stats.html
{% extends 'templates/main/header.html' %}
{% block main %}



{% if user.is_authenticated and user.is_parent%}
    <h2>Child Stats</h2>

    </br>
    <t>
        {{user.username|title}}
    </t>

    </br>


<div class="row">
	<div class="col-md">
		<div class="card card-body">
			<table class="table table-sm">
				<tr>
                    <th>Name</th>
                    <th>Absent</th>
                    <th>Late</th>
                    <th>Ontime</th>
                    <th>In school today?</th>
				</tr>


				{% for name, cnt, l_cnt, p_cnt, p_today in att_list %}

				<tr>
                    <td>{{name}}</td>
                    <td>{{cnt}}</td>
                    <td>{{l_cnt}}</td>
                    <td>{{p_cnt}}</td>
                    <td>{{p_today}}</td>
				</tr>
				{% endfor %}

			</table>
		</div>
	</div>
</div>

</br>
</br>

<div class="form-row">
    <div id="container" style="width: 75%;">
        <canvas id="pie-chart"></canvas>
    </div>
    <h4>
        <div class="card col-md6" style="width: 23rem;">
          <ul class="list-group list-group-flush">
             {% for l in logs_parsed %}
               {% for log in l %}
              <li class="list-group-item"></br>{{log}}</br></li>
                 </br>
                {%endfor %}
              {%endfor%}
          </ul>
        </div>
    </h4>

</div>


  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script>

    var config = {
      type: 'pie',
      data: {
        datasets: [{
          data: {{ data|safe }},
          backgroundColor: [
            '#6170d1', '#4d79ff', '#A9A9A9', '#C0C0C0', '#D3D3D3'
          ],
          label: 'Population'
        }],
        labels: {{ labels|safe }}
      },
      options: {
        responsive: true
      }
    };

    window.onload = function() {
      var ctx = document.getElementById('pie-chart').getContext('2d');
      window.myPie = new Chart(ctx, config);
    };

  </script>



{% else %}
    <t>
        login first as parent
    </t>
{% endif %}


{% endblock %}

mysite/mysite/main/templates/main/contactus.html
{% extends 'templates/main/header.html' %}


{% block content %}

    Contact us at andrew.concejero@gmail.com if you have any concerns.

    If you already have an account <a href="/login" target="blank"><strong>login</strong></a> here.
    If you dont, <a href="/register" target="blank"><strong>signup</strong></a> here.
{% endblock %}

mysite/mysite/main/templates/main/date.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Static Example</title>
  <style>body {font-family: Arial, sans-serif;}</style>

  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <!-- Fengyuan Chen's Datepicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
</head>
<body>
  <input id="datepicker">

  <script>
    $(function () {
      $("#datepicker").datepicker(
      {
      format:'yyyy/mm/dd'
      }
      );
    });
  </script>

</body>
</html>

mysite/mysite/main/templates/main/email.html
<!--<style type="text/css">-->
<!--.form-style-6{-->
<!--	font: 95% Arial, Helvetica, sans-serif;-->
<!--	max-width: 400px;-->
<!--	margin: 10px auto;-->
<!--	padding: 16px;-->
<!--	background: #F7F7F7;-->
<!--}-->
<!--.form-style-6 h1{-->
<!--	background: #43D1AF;-->
<!--	padding: 20px 0;-->
<!--	font-size: 140%;-->
<!--	font-weight: 300;-->
<!--	text-align: center;-->
<!--	color: #fff;-->
<!--	margin: -16px -16px 16px -16px;-->
<!--}-->
<!--.form-style-6 input[type="text"],-->
<!--.form-style-6 input[type="date"],-->
<!--.form-style-6 input[type="datetime"],-->
<!--.form-style-6 input[type="email"],-->
<!--.form-style-6 input[type="number"],-->
<!--.form-style-6 input[type="search"],-->
<!--.form-style-6 input[type="time"],-->
<!--.form-style-6 input[type="url"],-->
<!--.form-style-6 textarea,-->
<!--.form-style-6 select-->
<!--{-->
<!--	-webkit-transition: all 0.30s ease-in-out;-->
<!--	-moz-transition: all 0.30s ease-in-out;-->
<!--	-ms-transition: all 0.30s ease-in-out;-->
<!--	-o-transition: all 0.30s ease-in-out;-->
<!--	outline: none;-->
<!--	box-sizing: border-box;-->
<!--	-webkit-box-sizing: border-box;-->
<!--	-moz-box-sizing: border-box;-->
<!--	width: 100%;-->
<!--	background: #fff;-->
<!--	margin-bottom: 4%;-->
<!--	border: 1px solid #ccc;-->
<!--	padding: 3%;-->
<!--	color: #555;-->
<!--	font: 95% Arial, Helvetica, sans-serif;-->
<!--}-->
<!--.form-style-6 input[type="text"]:focus,-->
<!--.form-style-6 input[type="date"]:focus,-->
<!--.form-style-6 input[type="datetime"]:focus,-->
<!--.form-style-6 input[type="email"]:focus,-->
<!--.form-style-6 input[type="number"]:focus,-->
<!--.form-style-6 input[type="search"]:focus,-->
<!--.form-style-6 input[type="time"]:focus,-->
<!--.form-style-6 input[type="url"]:focus,-->
<!--.form-style-6 textarea:focus,-->
<!--.form-style-6 select:focus-->
<!--{-->
<!--	box-shadow: 0 0 5px #43D1AF;-->
<!--	padding: 3%;-->
<!--	border: 1px solid #43D1AF;-->
<!--}-->

<!--.form-style-6 input[type="submit"],-->
<!--.form-style-6 input[type="button"]{-->
<!--	box-sizing: border-box;-->
<!--	-webkit-box-sizing: border-box;-->
<!--	-moz-box-sizing: border-box;-->
<!--	width: 100%;-->
<!--	padding: 3%;-->
<!--	background: #43D1AF;-->
<!--	border-bottom: 2px solid #30C29E;-->
<!--	border-top-style: none;-->
<!--	border-right-style: none;-->
<!--	border-left-style: none;-->
<!--	color: #fff;-->
<!--}-->
<!--.form-style-6 input[type="submit"]:hover,-->
<!--.form-style-6 input[type="button"]:hover{-->
<!--	background: #2EBC99;-->
<!--}-->
<!--</style>-->


<div class="form-style-6">
    <h1>Contact Us</h1>
    <form>
        <input type="text" name="field1" placeholder="Your Name" />
        <input type="email" name="field2" placeholder="Email Address" />
        <textarea name="field3" placeholder="Type your Message"></textarea>
    </br>
    </form>
    <h1>Submitted</h1>
</div>

mysite/mysite/main/templates/main/header.html
<!--<head>-->
<!--    {% load static %}-->
<!--    &lt;!&ndash; Prism CSS &ndash;&gt;-->
<!--    <link href="{% static "tinymce/css/prism.css" %}" rel="stylesheet">-->
<!--    &lt;!&ndash; Compiled and minified CSS &ndash;&gt;-->
<!--    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">-->
<!--    &lt;!&ndash; Compiled and minified JavaScript &ndash;&gt;-->
<!--    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>-->
<!--</head>-->


<!--<body>-->
<!--  <nav>-->
<!--    <div class="nav-wrapper">-->
<!--      <a href="/" class="brand-logo">Student Attendance Tracking System</a>-->
<!--      <ul id="nav-mobile" class="right hide-on-med-and-down">-->
<!--        <li><a href="/">Home</a></li>-->
<!--         {% if user.is_authenticated %}-->
<!--             <li><a href="/account">{{user.username|title}}</a></li>-->
<!--             <li><a href="/logout">Logout</a></li>-->
<!--        {% else %}-->
<!--            <li><a href="/login">Login</a></li>-->
<!--        {% endif %}-->
<!--          <li><a href="/contact_us">Contact Us</a></li>-->
<!--      </ul>-->
<!--    </div>-->
<!--  </nav>-->


<!--  <div class = "container">-->
<!--      {% block content %}-->
<!--      {% endblock %}-->

<!--  </div>-->

<!--</body>-->

<!--&lt;!&ndash; Prism JS &ndash;&gt;-->
<!--<script src="{% static "tinymce/js/prism.js" %}"></script>-->

<!doctype html>
<html lang="en">
  <head>
	  {% load static %}

  	<title>Hound</title>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">



    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="{% static "css/style.css" %}">

	  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">


 
  </head>
  <body>

		<div class="wrapper d-flex align-items-stretch">
			<nav id="sidebar">
				<div class="custom-menu">
					<button type="button" id="sidebarCollapse" class="btn btn-primary">
	          <i class="fa fa-bars"></i>
	          <span class="sr-only">Toggle Menu</span>
	        </button>
        </div>
				<div class="p-4">
		  		<h1><a href="/" class="logo">Hound     <i class="fa fa-map-marker" aria-hidden="true"></i>
					<span>Student Attendance</span><span> Tracking System</span></a></h1>
	        <ul class="list-unstyled components mb-5">

	          <li class="active">
	            <a href="/"><span class="fa fa-home mr-3"></span> Home</a>
	          </li>
			  <li>
	            <a href="/"><span class="fa fa-pencil-square-o mr-3"></span> Register</a>
	          </li>
			 {% if user.is_authenticated %}
				 <li><a href="/account"> <span class = "fa fa-user mr-3"> </span>  {{user.username|title}}</a></li>
				{% if user.is_parent %}
					{% for student in students%}
						{% for sp in student.parent.all %}
							{%if sp.user.id == user.id %}
								<li><a href="/child_stats/{{student.first_name}}">
									<span class = "fa fa-graduation-cap mr-3"> </span>{{student.first_name}}</a></li>
							{% endif %}
						{% endfor %}
					{% endfor %}

   					<li><a href="/calendar"><span class = "fa fa-calendar mr-3"> </span> Calendar</a></li>
					<li><a href="/calendar-new"><span class = "fa fa-calendar mr-3"> </span> Calendar2</a></li>
				{%endif %}
<!--				admin-->
				{% if user.id == 5 %}
					<li><a href="/students"> <span class = "fa fa-search mr-3"> </span> Section</a></li>
				{%endif %}

				{% if user.is_teacher %}
					<li><a href="/stud_attendance"> <span class = "fa fa-search mr-3"> </span> Section</a></li>
				{%endif %}

			{% else %}
				<li><a href="/login"><span class = "fa fa-sign-in mr-3"> </span> Login</a></li>
			{% endif %}
			  <li><a href="/contact_us"><span class="fa fa-paper-plane mr-3"></span> Contact Us</a>	</li>



			</br>
			</br>
			</br>
			</br>
			</br>
			</br>
			</br>
			</br>
			</br>
			</br>
			</br>
			</br>
			</br>

			{% if user.is_authenticated %}
			<li><a href="/logout"><span class = "fa fa-sign-out mr-3"> </span> Logout</a></li>
			{% endif %}

      </ul>

<!--	          <li>-->
<!--	              <a href="#"><span class="fa fa-user mr-3"></span> About</a>-->
<!--	          </li>-->
<!--	          <li>-->
<!--              <a href="#"><span class="fa fa-briefcase mr-3"></span> Works</a>-->
<!--	          </li>-->
<!--	          <li>-->
<!--              <a href="#"><span class="fa fa-sticky-note mr-3"></span> Blog</a>-->
<!--	          </li>-->
<!--	          <li>-->
<!--              <a href="#"><span class="fa fa-suitcase mr-3"></span> Gallery</a>-->
<!--	          </li>-->
<!--	          <li>-->
<!--              <a href="#"><span class="fa fa-cogs mr-3"></span> Services</a>-->
<!--	          </li>-->
<!--	          <li>-->
<!--              <a href="#"><span class="fa fa-paper-plane mr-3"></span> Contacts</a>-->
<!--	          </li>-->
	        </ul>

<!--	        <div class="mb-5">-->
<!--						<h3 class="h6 mb-3">Subscribe for newsletter</h3>-->
<!--						<form action="#" class="subscribe-form">-->
<!--	            <div class="form-group d-flex">-->
<!--	            	<div class="icon"><span class="icon-paper-plane"></span></div>-->
<!--	              <input type="text" class="form-control" placeholder="Enter Email Address">-->
<!--	            </div>-->
<!--	          </form>-->
<!--					</div>-->

<!--	        <div class="footer">-->
<!--	        	<p>&lt;!&ndash; Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. &ndash;&gt;-->
<!--						  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib.com</a>-->
<!--						  &lt;!&ndash; Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. &ndash;&gt;</p>-->
<!--	        </div>-->

	      </div>
    	</nav>

        <!-- Page Content  -->

      <div id="content" class="p-4 p-md-5 pt-5">

		{% include 'templates/main/messaging.html' %}
<!--	  	<div class = "container">-->
<!--			  {% block title %}-->
<!--			  {% endblock %}-->

<!--		</div>-->

        <h2 class="mb-4">
			{% block main %}
			{% endblock %}
		</h2>


<!--        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>-->
<!--        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>-->
      </div>

		</div>

    <script src="{% static "js/jquery.min.js" %}"></script>
	<script src="{% static "js/popper.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/main.js" %}"></script>


  	<script>
    setTimeout(function(){
      if ($('#msg').length > 0) {
        $('#msg').remove();
      }
    }, 10000)
  </script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
  </body>
</html>

mysite/mysite/main/templates/main/signup_form.html
{% extends 'templates/main/header.html' %}

{% block main %}
  <div class="row">
    <div class="col-md-8 col-sm-10 col-12">
      <h2>Sign up as a {{ user_type }}</h2>
      <form method="post" novalidate>
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
<!--        {{ form}}-->
        {{form.errors}}

<!--        <tr>-->
<!--          <th><label for="id_username">Username:</label></th>-->
<!--          <td><input type="text" name="username" maxlength="150" autofocus required id="id_username">-->
<!--          <br><span class="helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span></td>-->
<!--        </tr>-->
<!--        </br>-->
<!--        <tr>-->
<!--          <th><label for="id_first_name">First name:</label></th>-->
<!--          <td><input type="text" name="first_name" maxlength="30" required id="id_first_name"></td>-->
<!--        </tr>-->
<!--        </br>-->
<!--        <tr>-->
<!--          <th><label for="id_middle_name">Middle name:</label></th>-->
<!--          <td><input type="text" name="middle_name" maxlength="30" required id="id_middle_name"></td>-->
<!--        </tr>-->
<!--        </br>-->
<!--        <tr>-->
<!--          <th><label for="id_last_name">Last name:</label></th>-->
<!--          <td><input type="text" name="last_name" maxlength="30" required id="id_last_name"></td>-->
<!--        </tr>-->
<!--        </br>-->
<!--        <tr>-->
<!--          <th><label for="id_password1">Password:</label></th>-->
<!--          <td><input type="password" name="password1" required id="id_password1"><br><span class="helptext"><ul>-->
<!--          <li>Your password can&#39;t be too similar to your other personal information.</li>-->
<!--          <li>Your password must contain at least 8 characters.</li>-->
<!--          <li>Your password can&#39;t be a commonly used password.</li>-->
<!--          <li>Your password can&#39;t be entirely numeric.</li></ul></span></td>-->
<!--        </tr>-->
<!--        </br>-->
<!--        <tr>-->
<!--          <th><label for="id_password2">Password confirmation:</label></th>-->
<!--          <td><input type="password" name="password2" required id="id_password2">-->
<!--          <br><span class="helptext">Enter the same password as before, for verification.</span></td>-->
<!--        </tr>-->

        </br>

          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="id_username">Username</label>
              <input type="text" name="username" maxlength="150" autofocus required  id="id_username">
              <br><h6><span class="helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span></h6>
            </div>
          </div>

           <div class="form-row">
            <div class="form-group col-md-6">
              <label for="id_first_name">First Name</label>
              <input type="text" name="first_name" maxlength="30" required  id="id_first_name">
            </div>
            <div class="form-group col-md-6">
              <label for="id_middle_name">Middle Name</label>
              <input type="text" name="middle_name" maxlength="30" required id="id_middle_name">
            </div>
             <div class="form-group col-md-6">
              <label for="id_last_name">Last Name</label>
              <input type="text" name="last_name" maxlength="30" required  id="id_last_name">
            </div>
          </div>

          {% if parent %}
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="id_phone">Phone Number</label>
              <input type="tel" name="phone" required autofocus required  id="id_phone" >
              <br><h6><span class="helptext">Number should start with +63</span></h6>
            </div>
          </div>
          {% endif %}

          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="id_password1">Password</label>
              <input type="password" name="password1" required id="id_password1">
              <h6>
                <br><span class="helptext"><ul>
                <li>Your password can&#39;t be too similar to your other personal information.</li>
                <li>Your password must contain at least 8 characters.</li>
                <li>Your password can&#39;t be a commonly used password.</li>
                <li>Your password can&#39;t be entirely numeric.</li></ul></span>
              </h6>
            </div>
            <div class="form-group col-md-6">
              <label for="id_password2">Password Confirmation</label>
              <input type="password" name="password2" required  id="id_password2">
              <h6>
                <br><span class="helptext">Enter the same password as before, for verification.</span>
              </h6>

           </div>
            </br>


          <button type="submit" class="btn btn-primary">Sign up</button>
<!--          <button type="submit" class="btn btn-success">Sign up</button>-->
        </form>


{% endblock %}